version: '3.8'

services:
  frontend:
    build: .
    image: shatterplayer/portfolio
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ./src:/app/src:ro
